FROM alpine:latest

COPY . /idata
# WORKDIR /data

# #grabs interaction file from STRING website
# RUN wget https://stringdb-static.org/download/protein.links.v11.5/9606.protein.links.v11.5.txt.gz 
# #grabs mappings
# RUN wget https://stringdb-static.org/download/protein.aliases.v11.5/9606.protein.aliases.v11.5.txt.gz

# RUN export DATA=/data

CMD ["sleep", "infinity"]