version: "3"
services:
  minio: # Data storage container 
      image: minio/minio:latest # Pull from dockerhub
      container_name: minio-map
      ports:
          - "9000:9000"
          - "9001:9001"
      command: server /data --console-address ':9001'
  enrich_app:
    # build: .
    image: enrich_app
    ports: 
      - 8080:8080
    #volumes:
    # - /Users/lewi052/enrich_proj/NEATO/app/test_data/test_yeast.csv:/app/test_data/test_yeast.csv
    # - /Users/lewi052/enrich_proj/NEATO/app/global.R:/app/global.R
    # - /Users/lewi052/enrich_proj/NEATO/app/String.R:/app/String.R
    # - /Users/lewi052/enrich_proj/NEATO/app/ui.R:/app/ui.R
    # - /Users/lewi052/enrich_proj/NEATO/app/enrichment.R:/app/enrichment.R
    # - /Users/lewi052/enrich_proj/NEATO/app/server.R:/app/server.R
    # - /Users/lewi052/enrich_proj/NEATO/app/Enrichment_db:/app/Enrichment_db
    # - /Users/lewi052/enrich_proj/NEATO/app/www/bootstrap.css:/app/www/bootstrap.css
    # - /Users/lewi052/enrich_proj/NEATO/app/www/neato.jpeg:/app/www/neato.jpeg
    # - /Users/lewi052/enrich_proj/NEATO/app/www/about_neato.md:/app/www/about_neato.md
    environment:
      - DEMO_VERSION="1"
      - SHINYPROXY_USERNAME=test_user #change too $SHINYPROXY_USERNAME when deploying on cloud
  neatodata-service:
    image: neato_service # Build 
    container_name: neato_service
    # volumes:
    #  - "/Users/lewi052/enrich_proj/NEATO/app/NEATO-Service/rworker.R:/rworker.R"
    #  - "/Users/lewi052/enrich_proj/NEATO/app/NEATO-Service/String.R:/String.R"
    # - "/Users/lewi052/enrich_proj/NEATO/app/NEATO-Service/STRING_db:/STRING_db"
    environment:
      - DEMO_VERSION="1"
      - SHINYPROXY_USERNAME=test_user #change too $SHINYPROXY_USERNAME when deploying on cloud
    ports:
        - "8081:3838"
  redis1: # The "job board" container
    image: redis:latest # Pull from dockerhub
    container_name: redis1
    expose: 
        - "6379"
    ports: 
        - "6379:6379"