version: "3"
services:
  minio: # Data storage container 
      image: minio/minio:latest # Pull from dockerhub
      container_name: minio-map
      ports:
          - "9000:9000"
          - "9001:9001"
      command: server /data --console-address ':9001'
  enrich_app:
    # build: .
    image: enrich_app
    privileged: true
    ports: 
      - 8080:8080
    volumes:
      - inters:/idata
      # - output_data:/out_data
      - enrich:/edata
      - ./global.R:/app/global.R #get rid of this when rebuilding
      - ./server.R:/app/server.R
      - ./ui.R:/app/ui.R
      - ./minio_config.yml:/app/minio_config.yml #get rid of this when rebuilding
      - ./redis_config.yml:/app/redis_config.yml
      - ./www/bootstrap.css:/app/www/bootstrap.css
    environment:
      - SHINYPROXY_USERNAME=test_user # Required to create folder in minio
      - DEMO_VERSION="1"
  inters_db:
    image: loglew12/inters_db:latest
    volumes:
      - inters:/idata
  enrich_db:
    image: loglew12/enrich_db:latest
    volumes:
      - enrich:/edata
  neatodata-service:
    image: neato_service # Build 
    container_name: neato_service
    volumes:
      - inters:/idata
      - enrich:/edata
      - "./NEATO-Service/minio_config.yml:/minio_config.yml" # Service needs to connect to minio
      - "./NEATO-Service/redis_config.yml:/redis_config.yml" # Service needs to connect to redis
      - "./NEATO-Service/rworker.R:/rworker.R"
    environment:
        - SHINYPROXY_USERNAME=test_user
    ports:
        - "8081:3838"
  redis1: # The "job board" container
    image: redis:latest # Pull from dockerhub
    container_name: redis1
    expose: 
        - "6379"
    ports: 
        - "6379:6379"

volumes:
  inters:
  enrich:
  output_data: