---
title: "clusterProfiler_practice"
author: "Logan Lewis"
date: '2022-04-15'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(stringr)
library(org.Hs.eg.db)
library("clusterProfiler")
```

```{r}
proStat <- readRDS("/Users/lewi052/MAP/STRINGdb_exploration/proStat2.RDS")
```

```{r}
#grabbing statistically significant and differentially expressed proteins
proStat_HvS <- proStat %>% filter(`P_value_A_Healthy Control_vs_Severe`<0.05) %>% filter(`Flag_A_Healthy Control_vs_Severe` != 0)
```

```{r}
#creating a gene list with logFC as values, UNIPROT identifiers as names, and ordering them by logFC (all needed for gseGO())
geneList_HvS <- proStat_HvS[,10]
names(geneList_HvS) = as.character(proStat_HvS[,17])
geneList_HvS = sort(geneList_HvS, decreasing = TRUE)
```

```{r}
# GO term classification of genes
ggo <- groupGO(gene     = proStat_HvS$Protein_Identifier,
               OrgDb    = org.Hs.eg.db,
               keyType = "UNIPROT",
               ont      = "CC",
               level    = 3,
               readable = TRUE)
```

```{r}
ggo[order(ggo$GeneRatio, decreasing = T), ]
```

```{r}
# GO Gene set enrichment analysis
ego3 <- gseGO(geneList     = geneList_HvS,
              OrgDb        = org.Hs.eg.db,
              keyType = "UNIPROT",
              ont          = "CC",
              verbose      = FALSE)
```

```{r}
ego3_ordered <- ego3[order(ego3$enrichmentScore), ]
head(ego3_ordered, n=75)
```
```{r}
goplot(ego3)
```




