---
title: "PCSF"
author: "Logan Lewis"
date: '2022-04-23'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("PCSF")
library("tidyverse")
library("UniProt.ws")
library(org.Hs.eg.db)
library(tidyverse)
data("STRING")
data("Tgfb_phospho")
```

```{r}
columns(org.Hs.eg.db)
```

```{r}
proStat <- readRDS("/Users/lewi052/MAP/STRINGdb_exploration/proStat2.RDS")
```

```{r}
proStat_HvS <- proStat %>% filter(`P_value_A_Healthy Control_vs_Severe`<0.05) %>% filter(`Flag_A_Healthy Control_vs_Severe` != 0)

geneList_HvS <- abs(proStat_HvS[,10])
gene_sym <- UniProt.ws::select(org.Hs.eg.db, proStat_HvS[,17], "SYMBOL","UNIPROT")
gene_sym <- gene_sym[!duplicated(gene_sym[,1]),]
# for (i in 1:length(gene_sym[,2])) {
#   if (is.na(gene_sym[i,2])) {
#     gene_sym[i,2] <- gene_sym[i,1]
#   }
# }


names(geneList_HvS) = as.character(gene_sym[,2])
terminals <- geneList_HvS
```
```{r}
map_to_stringids <- function(filtUserData, m_db){
  mapping <- dplyr::filter(m_db, m_db$alias %in% filtUserData$Protein_Identifier)
  mapping <- mapping[!duplicated(mapping$alias),]
  colnames(mapping) <- c("STRING_id","Protein_Identifier", "source")

  filtUserData <- left_join(filtUserData, mapping, by = "Protein_Identifier")

  mapped_stat <- drop_na(filtUserData)
  print(nrow(filtUserData))
  print(nrow(mapped_stat))
  return(mapped_stat)
}

prepare_interactome <- function(inters_db = inters_db){
  interactome <- as.data.frame(inters_db[, c("protein1", "protein2", "combined_score")])
  interactome$combined_score = ((1000 - interactome$combined_score)/1000)
  interactome <- construct_interactome(interactome)
  return(interactome)
}
```


````{r}
colnames(proStat)[which(names(proStat) == "Fold_change_Healthy Control_vs_Severe")] <- "Fold_change"
proStat <- mutate(proStat, Fold_change_abs = abs(proStat$Fold_change))
proStat <- proStat[order(proStat$`Fold_change_abs`, decreasing = T), ]

terminals <- proStat$Fold_change_abs[1:150]
hits <- proStat[1:150, ]
hits <- map_to_stringids(hits, mapping_db)
names(terminals) = as.character(hits$STRING_id)

ppi <- prepare_interactome(inters_db = inters_db)
subnet <- PCSF(ppi, terminals, w = 2, b = 1, mu = 0.0005)
names <- convert_to_genename(unlist(V(subnet)$name), mapping_db = mapping_db)
V(subnet)$name <- names
class(subnet)
```

```{r}
E(subnet)$value <- E(subnet)$weight
visIgraph(subnet) %>% visIgraphLayout()
```


```{r}
geneList_HvS <- sort(geneList_HvS, decreasing = T)
terminals <- geneList_HvS[1:50]
ppi <- construct_interactome(STRING)
subnet <- PCSF(ppi, terminals, w = 2, b = 1, mu = 0.0005)
V(subnet)$name
plot(subnet, style = 1, node_size = 20, node_label_cex = 10, Terminal_node_color = "red")
```

```{r}
res <- enrichment_analysis(subnet)
class(res$subnet)
en_tab <- res$enrich
plot(res$subnet)
```

```{r}
V(res$subnet)$group[V(res$subnet)$name == "ALK"]
```

```{r}
library("PCSF")
data("STRING")
data("Tgfb_phospho")
terminals <- Tgfb_phospho
ppi <- construct_interactome(STRING)
subnet <- PCSF_rand(ppi, terminals, n = 10, r = 0.1, w = 2, b = 1, mu = 0.0005)
res <- enrichment_analysis(subnet)
plot(res$subnet)
```
```{r}
class(E(res$subnet)$weight)
```

